# Importing numpy


In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 0D Arrays or Scalars


In [3]:
arr = np.array(42)
print(arr)

42


## 1D array

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2D Array

In [5]:
arr = np.array(((1,2,3),(4,5,6)))
print(arr)

[[1 2 3]
 [4 5 6]]


## 3D Array

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Checking dimension

In [7]:
a = np.array(15)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2], [3, 4]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher dimesional arrays

In [8]:
##can use ndmin arguement to create ndimensional arrays

arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# NUMPY ARRAY INDEXING

## Accessing array elements

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


## Accessing 2D Arrays

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])

2


In [11]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,4])

11


## Accessing 3D Arrays

In [12]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(arr[0,1,2])

7


## Negative Indexing

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr[-1,-3])

6


# NUMPY ARRAY SLICING

## Slicing Arrays

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:5])


[2 3 4 5]


In [17]:
print(arr[4:])

[5 6 7 8]


In [18]:
print(arr[:4])

[1 2 3 4]


In [19]:
print(arr[-3:])

[6 7 8]


In [20]:
print(arr[1:5:2])

[2 4]


In [21]:
print(arr[::2])

[1 3 5 7]


## Slicing 2D Arrays

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 20]])

In [23]:
print(arr[1,2:4])

[8 9]


In [24]:
print(arr[1,1:4])

[7 8 9]


In [26]:
print(arr[0:2, 2])

[3 8]


In [27]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# DATA TYPES

data types in python:
    Strings,Boolean,Integer,Float,Complex

data types in numpy:
    S - string
    b - boolean
    i - integer
    f - float
    c - complex float
    u - unsigned int
    U - unicode string
    m - timedelta
    M - datetime
    O - object
    V - void

## Checking datatype of array

In [28]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int64


In [32]:
arr = np.array(["Apple", "Banana", "Cherry"])
print(arr.dtype)

<U6


In [33]:
arr = np.array([True, False])
print(arr.dtype)

bool


## Creating arrays with defined datatype


In [47]:
arr = np.array([1,20,3,4],dtype="S")
print(arr)

print(arr.dtype)

[b'1' b'20' b'3' b'4']
|S2


In [45]:
arr = np.array([1,12,123,1234,12345,123456],dtype='i4')
print(arr)
print(arr.dtype)


[     1     12    123   1234  12345 123456]
int32


## What if value cannot be converted

In [53]:
arr = np.array(['a',2, 3],dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

## Change datatype of existing array

In [56]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

newArr = arr.astype('f')
print(newArr)
print(newArr.dtype)

int64
[1. 2. 3. 4. 5.]
float32


In [60]:
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

newArr = arr.astype("bool")
print(newArr)
print(newArr.dtype)

newnewArr = newArr.astype("i")
print(newnewArr)
print(newnewArr.dtype)

int64
[False  True  True  True  True  True]
bool
[0 1 1 1 1 1]
int32


# NUMPY COPY vs VIEW

In [70]:
arr = np.array([1, 2, 3, 3, 4, 5])
copyArr = arr.copy()
arr[0] = 49

print(arr)
print(copyArr)

[49  2  3  3  4  5]
[1 2 3 3 4 5]


In [72]:
arr = np.array([1, 2, 3, 4, 5])
viewArr = arr.view()

arr[1] = 38
print(arr)
print(viewArr)

viewArr[0]=49
print(arr)
print(viewArr)


[ 1 38  3  4  5]
[ 1 38  3  4  5]
[49 38  3  4  5]
[49 38  3  4  5]


## Check array own its data

In [76]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.base)

copyArr = arr.copy()
print(copyArr.base)

viewArr = arr.view()
print(viewArr.base)

None
None
[1 2 3 4 5]
