# Importing numpy


In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 0D Arrays or Scalars


In [3]:
arr = np.array(42)
print(arr)

42


## 1D array

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2D Array

In [5]:
arr = np.array(((1,2,3),(4,5,6)))
print(arr)

[[1 2 3]
 [4 5 6]]


## 3D Array

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Checking dimension

In [7]:
a = np.array(15)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2], [3, 4]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher dimesional arrays

In [8]:
##can use ndmin arguement to create ndimensional arrays

arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# NUMPY ARRAY INDEXING

## Accessing array elements

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


## Accessing 2D Arrays

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])

2


In [11]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,4])

11


## Accessing 3D Arrays

In [12]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(arr[0,1,2])

7


## Negative Indexing

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr[-1,-3])

6


# NUMPY ARRAY SLICING

## Slicing Arrays

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:5])


[2 3 4 5]
