# Importing numpy


In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 0D Arrays or Scalars


In [3]:
arr = np.array(42)
print(arr)

42


## 1D array

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2D Array

In [5]:
arr = np.array(((1,2,3),(4,5,6)))
print(arr)

[[1 2 3]
 [4 5 6]]


## 3D Array

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Checking dimension

In [7]:
a = np.array(15)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2], [3, 4]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher dimesional arrays

In [8]:
##can use ndmin arguement to create ndimensional arrays

arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# NUMPY ARRAY INDEXING

## Accessing array elements

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


## Accessing 2D Arrays

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])

2


In [11]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,4])

11


## Accessing 3D Arrays

In [12]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(arr[0,1,2])

7


## Negative Indexing

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr[-1,-3])

6


# NUMPY ARRAY SLICING

## Slicing Arrays

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:5])


[2 3 4 5]


In [17]:
print(arr[4:])

[5 6 7 8]


In [18]:
print(arr[:4])

[1 2 3 4]


In [19]:
print(arr[-3:])

[6 7 8]


In [20]:
print(arr[1:5:2])

[2 4]


In [21]:
print(arr[::2])

[1 3 5 7]


## Slicing 2D Arrays

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 20]])

In [23]:
print(arr[1,2:4])

[8 9]


In [24]:
print(arr[1,1:4])

[7 8 9]


In [26]:
print(arr[0:2, 2])

[3 8]


In [27]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# DATA TYPES

data types in python:
    Strings,Boolean,Integer,Float,Complex

data types in numpy:
    S - string
    b - boolean
    i - integer
    f - float
    c - complex float
    u - unsigned int
    U - unicode string
    m - timedelta
    M - datetime
    O - object
    V - void

## Checking datatype of array

In [28]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int64


In [32]:
arr = np.array(["Apple", "Banana", "Cherry"])
print(arr.dtype)

<U6


In [33]:
arr = np.array([True, False])
print(arr.dtype)

bool


## Creating arrays with defined datatype


In [47]:
arr = np.array([1,20,3,4],dtype="S")
print(arr)

print(arr.dtype)

[b'1' b'20' b'3' b'4']
|S2


In [45]:
arr = np.array([1,12,123,1234,12345,123456],dtype='i4')
print(arr)
print(arr.dtype)


[     1     12    123   1234  12345 123456]
int32


## What if value cannot be converted

In [53]:
arr = np.array(['a',2, 3],dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

## Change datatype of existing array

In [56]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

newArr = arr.astype('f')
print(newArr)
print(newArr.dtype)

int64
[1. 2. 3. 4. 5.]
float32


In [60]:
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

newArr = arr.astype("bool")
print(newArr)
print(newArr.dtype)

newnewArr = newArr.astype("i")
print(newnewArr)
print(newnewArr.dtype)

int64
[False  True  True  True  True  True]
bool
[0 1 1 1 1 1]
int32


# NUMPY COPY vs VIEW

In [70]:
arr = np.array([1, 2, 3, 3, 4, 5])
copyArr = arr.copy()
arr[0] = 49

print(arr)
print(copyArr)

[49  2  3  3  4  5]
[1 2 3 3 4 5]


In [72]:
arr = np.array([1, 2, 3, 4, 5])
viewArr = arr.view()

arr[1] = 38
print(arr)
print(viewArr)

viewArr[0]=49
print(arr)
print(viewArr)


[ 1 38  3  4  5]
[ 1 38  3  4  5]
[49 38  3  4  5]
[49 38  3  4  5]


## Check array own its data

In [76]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.base)

copyArr = arr.copy()
print(copyArr.base)

viewArr = arr.view()
print(viewArr.base)

None
None
[1 2 3 4 5]


# NUMPY ARRAY SHAPE 

In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [80]:
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [82]:
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr.shape)

(1, 1, 1, 1, 5)


In [85]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.shape)

(2, 3, 3)


# NUMPY ARRAY RESHAPING

# Reshape from 1D to 2D

In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newArr = arr.reshape(4,3)

print(newArr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape from 1D to 3D

In [88]:
newArr = arr.reshape(2,3,2)
print(newArr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can we reshape into any shape

### Yes,as long as elements required for reshaping are equal in both shapes

In [92]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newArr = arr.reshape(3,3)

print(newArr)

ValueError: cannot reshape array of size 8 into shape (3,3)

## Returns copy or view

In [108]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reshaped_arr =arr.reshape(2, 4)

print(reshaped_arr.base)

[1 2 3 4 5 6 7 8]


## Unknown Dimension

In [111]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reshaped_array = arr.reshape(2,2,-1)

print(reshaped_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flatten Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# newArr = arr.flatten()
newArr = arr.reshape(-1)


print(arr)
print(newArr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# NUMPY ARRAY ITERATING

## Iterating 1D Array

In [118]:
arr = np.array([1,2,3,4,5,6,7,8])

for x in arr:
    print(x)

1
2
3
4
5
6
7
8


## Iterating 2D Array

In [120]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## Iterating 3D Array

In [123]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6


## Iterating using nditer

In [126]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
1
2
3
4
5
6


## Iterating array with different datatypes


In [131]:
arr = np.array([1,2,3,4,5,6])

for x in np.nditer(arr,flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


## Iterating with different step size

In [133]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
6
8
10


## Iterating using ndenumerate

In [134]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

for index,value in np.ndenumerate(arr):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10


In [135]:
arr = np.array([[1,2,3],[4,5,6]])

for index,value in np.ndenumerate(arr):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# NUMPY JOINING ARRAYS

## Joining arrays

In [137]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([21,21,23,24,25])

arr = np.concatenate((arr1,arr2))

print(arr)

[ 1  2  3  4  5 21 21 23 24 25]


In [142]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Joining arrays using stack function

In [150]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1,arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking along rows

In [154]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking along columns

In [155]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr = np.vstack((arr1,arr2))

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Stacking along height(depth)

In [161]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

arr = np.dstack((arr1,arr2))
print(arr)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


# NUMPY SPLITTING ARRAYS

In [166]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [167]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [169]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,3)

print(newarr[2])
print(newarr[1])
print(newarr[0])

[5 6]
[3 4]
[1 2]


## Splitting 2D Arrays

In [170]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr,3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [172]:
arr = np.array(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]
)

newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [179]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [180]:
arr = np.array(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]
)

newarr = np.hsplit(arr,3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NUMPY SEARCHING ARRAYS

In [189]:
arr = np.array([1, 2, 3, 4, 5, 3, 6, 7, 3])

res = np.where(arr == 3)
print(res)


(array([2, 5, 8]),)


In [191]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
res_even = np.where(arr%2 == 0)
print(res_even)

res_odd = np.where(arr%2 != 0)
print(res_odd)

(array([1, 3, 5, 7, 9]),)
(array([0, 2, 4, 6, 8]),)


## Search Sorted


In [195]:
arr = np.array([1,2,3,4,5,6,7])
res = np.searchsorted(arr,3)

print(res)

2


## Search from right side

In [200]:
arr = np.array([5,6,7,8])
res = np.searchsorted(arr,6,side='right')

print(res)

2


### Multiple values

In [201]:
arr = np.array([7,9,10,14])
res = np.searchsorted(arr,[8,11])

print(res)

[1 3]


# NUMPY SORT

In [204]:
arr = np.array([9,3,6,1])
newarr = np.sort(arr)

print(f"arr : {arr}")
print(f"sortedarr : {newarr}")


arr : [9 3 6 1]
sortedarr : [1 3 6 9]


In [205]:
arr = np.array(["Banana","Mango","Orange","Apple","Cherry"])
newarr = np.sort(arr)

print(newarr)

['Apple' 'Banana' 'Cherry' 'Mango' 'Orange']


In [206]:
arr = np.array([True,False,True,False])
newarr = np.sort(arr)

print(newarr)

[False False  True  True]


## Sorting 2D Array

In [212]:
arr = np.array([[5,2,9],[4,1,8],[9,6,8]])
newarr = np.sort(arr)
print(newarr)

[[2 5 9]
 [1 4 8]
 [6 8 9]]


# NUMPY FILTER ARRAY

In [216]:
arr = np.array([5, 7, 3, 9, 1])

x = [True, False, True, False, True]


newarr = arr[x]

print(newarr)

[5 3 1]


## Creating filter Array

In [218]:
arr = np.array([5, 7, 3, 9, 1])

filter_arr = []

for elem in arr:
    if elem > 5:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False]
[7 9]


In [220]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for i in arr:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)
    

[False, True, False, True, False, True, False]
[2 4 6]


## Creating filter directly from array

In [221]:
arr = np.array([1, 2, 3, 4, 5, 6])

filter_arr = arr >3

newarr = arr[filter_arr]

print(newarr)

[4 5 6]


In [222]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(newarr)

[ 2  4  6  8 10]
