In [6]:
import numpy as np

# UFUNC INTRO


Vectorization: Converting terative statements into vector based operation

In [7]:
#Without ufunc

list1 = [1,2,3,4]
list2 = [9,10,11,12]

res_list = []


for i,j in zip(list1,list2):
    res_list.append(i+j)

print(res_list)

[10, 12, 14, 16]


In [8]:
#With ufunc

res_list2 = np.add(list1,list2)
print(res_list2)

[10 12 14 16]


# UFUNC CREATE

In [27]:
def mysub(x,y):
    return x - y

mysub = np.frompyfunc(mysub,2,1)

print(mysub([5,6,7,8],[4,1,3,1]))

[1 5 4 7]


In [31]:
#Type of ufunc

print(type(np.add))
print(type(mysub))
print(type(np.concatenate))
print(type(np.blabla))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


AttributeError: module 'numpy' has no attribute 'blabla'

In [32]:
if type(np.add)== np.ufunc:
    print("add is ufunc")
else:
    print("not ufunc")

add is ufunc


# UFUNC SIMPLE ARITHMETIC

## Addition

In [38]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([25, 26, 27, 28, 29, 30])

res_arr = np.add(arr1, arr2)
print(res_arr)

[35 37 39 41 43 45]


In [42]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([25, 26, 27, 28, 29, 30])
res_arr = np.array([4, 4, 4, 4, 4, 4])
np.add(arr1, arr2, where=arr1 % 2 == 0, out=res_arr)

print(res_arr)

[35  4 39  4 43  4]


## Subtraction

In [43]:
arr1 = np.array([25, 26, 27, 28, 29, 30])
arr2 = np.array([5, 10, 3, 18, 45,30])

res_arr = np.subtract(arr1,arr2)

print(res_arr)

[ 20  16  24  10 -16   0]


## Multiplication

In [44]:
arr1 = np.array([25, 26, 27, 28, 29, 30])
arr2 = np.array([5, 10, 3, 18, 45,30])

res_arr = np.multiply(arr1,arr2)
print(res_arr)

[ 125  260   81  504 1305  900]


## Division

In [45]:
arr1 = np.array([25, 26, 27, 28, 29, 30])
arr2 = np.array([5, 10, 3, 18, 45,30])

res_arr = np.divide(arr1,arr2)
print(res_arr)

[5.         2.6        9.         1.55555556 0.64444444 1.        ]


## Power

In [46]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 3, 2, 4])

res_arr = np.power(arr1,arr2)
print(res_arr)

[    100    8000     900 2560000]


## Remainder

In [49]:
arr1 = np.array([10, 20, 15, 39])
arr2 = np.array([2, 3, 2, 4])

res_arr = np.mod(arr1,arr2)

print(res_arr)

[0 2 1 3]


## Quotient and Mod

In [50]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

res_arr = np.divmod(arr1,arr2)
print(res_arr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values

In [51]:
arr = [-4, 1, -7, -8, 0, 2, 5]

res_arr = np.absolute(arr)

print(res_arr)

[4 1 7 8 0 2 5]


# NUMPY ROUNDING DECIMALS

In [54]:
# Truncation

arr = np.array([2, 3.5556, 2.33333, -1.5666, -2])

res_arr = np.trunc(arr)

print(res_arr)

[ 2.  3.  2. -1. -2.]


In [56]:
#fix

res_arr = np.fix(arr)
print(res_arr)

[ 2.  3.  2. -1. -2.]


In [71]:
# around

arr = [-1.2, 1.4, -1.5, 1.7, -1.9,]

res_arr = np.around(arr)

print(res_arr)

[-1.  1. -2.  2. -2.]


In [72]:
#floor

arr = [-1.2, 1.4, -1.5, 1.7, -1.9,]

res_arr = np.floor(arr)
print(res_arr)

[-2.  1. -2.  1. -2.]


In [73]:
#ceil

arr = [-1.2, 1.4, -1.5, 1.7, -1.9,]

res_arr = np.ceil(arr)
print(res_arr)

[-1.  2. -1.  2. -1.]


# NUMPY LOGS

In [ ]:
#base e or natural log
arr = np.arange(1,10)
print(arr)
print(np.log(arr))

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [78]:
#base2
arr = np.arange(1,10)
res_arr = np.log2(arr)
print(res_arr)

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [79]:
#base10

arr = np.arange(1,10)
res_arr = np.log10(arr)
print(res_arr)

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [84]:
#Log of any base

from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog([100,9], [15,2]))

[1.7005483074552052 3.1699250014423126]


# NUMPY SUMMATIONS

In [87]:
arr1 = np.arange(1,11)

res = np.sum([arr1])
print(res_arr)

55


In [88]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)
res = np.sum([arr1,arr2])
print(res)

110


In [91]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)

res = np.sum([arr1, arr2], axis=0)
print(res)

[ 2  4  6  8 10 12 14 16 18 20]


In [92]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)

res = np.sum([arr1, arr2], axis=1)
print(res)

[55 55]


In [90]:
#Cummulative Sum

arr = np.arange(1,11)

res_arr = np.cumsum(arr)

print(res_arr)

[ 1  3  6 10 15 21 28 36 45 55]


# Numpy Products

In [95]:
arr = np.arange(1,5)

res = np.prod(arr)
print(res)

24


In [98]:
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 9)

res_arr = np.prod([arr1, arr2])

print(res_arr)

40320


In [99]:
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 9)

res_arr = np.prod([arr1,arr2],axis=0)
print(res_arr)

[ 5 12 21 32]


In [100]:
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 9)

res_arr = np.prod([arr1,arr2],axis=1)
print(res_arr)

[  24 1680]


In [101]:
arr = np.arange(1,5)

res = np.cumprod([arr])

print(res)

[ 1  2  6 24]


# NUMPY DIFFERENCES

In [102]:
arr = np.array([1,5,7,3,15])

res_arr = np.diff(arr)

print(res_arr)

[ 4  2 -4 12]


In [103]:
arr = np.array([3, 19, 23, 16, 11, 4])

res_arr = np.diff(arr,n=2)

print(res_arr)

[-12 -11   2  -2]


# NUMPY LCM

In [104]:
#LCM of two numbers

res = np.lcm(4,5)
print(res)

20


In [105]:
# LCM of numbers in arrays
arr = np.arange(1,10)

res = np.lcm.reduce(arr)
print(res)

2520


# NUMPY GCD

In [107]:
res = np.gcd(9,12)
print(res)

3


In [114]:
#GCD of numbers in array

arr = np.array([20, 8, 32, 36, 16])
res = np.gcd.reduce(arr)
print(res)

4
